### ISSUE TITLE
aesni detection fatally fails with rustflags in ~/.cargo/config

### ISSUE THREAD

**Issue by FauxFaux** [RustCrypto/stream-ciphers#11] opened 2019-04-16 21:18 UTC
I have `target-cpu=native` set in my `rustflags`, in `~/.cargo/config`:
```
[target.'cfg(any(windows, unix))']
rustflags = ["-Ctarget-cpu=native"]
```

This causes `aes-ctr` to break my projects' build:
```
   Compiling aes-soft v0.3.3
   Compiling ctr v0.3.2
   Compiling aes-ctr v0.3.0
error[E0463]: can't find crate for `aesni`
  --> /home/faux/.cargo/registry/src/github.com-1ecc6299db9ec823/aes-ctr-0.3.0/src/lib.rs:62:1
   |
62 | extern crate aesni;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

I guess `cargo` is using different rules to interpret `target_feature` in `Cargo.toml` vs. during the build? Note how it is loading the `aes-soft` crate above.

I tested stable and nightly `cargo`:
cargo 1.35.0-nightly (6f3e9c367 2019-04-04)
cargo 1.34.0 (6789d8a0a 2019-04-01)

If I remove `~/.cargo/config`, and instead set `RUSTFLAGS=`, everything seems to work as expected:

```
% RUSTFLAGS=-Ctarget-cpu=native cargo build
...
   Compiling aesni v0.6.0
   Compiling aes-ctr v0.3.0
   Compiling lol v0.1.0 (/var/tmp/faux190416.sciatica/lol)
```

**Comment by newpavlov** [comment] 2019-04-17 04:04
Looks like a `cargo` bug, which I've confirmed with an empty project. For some reason `.cargo/config` does not work for `cfg`s in `Cargo.toml`. Can you create an issue in [rust-lang/cargo](https://github.com/rust-lang/cargo/) repository?

**Comment by newpavlov** [comment] 2019-04-18 23:01
I will close this issue in favor of the linked issue.

**Closed by newpavlov** 2019-04-18 23:01 UTC

**Comment by dvdplm** [comment] 2019-06-18 05:13
Before https://github.com/rust-lang/cargo/issues/6858 gets a fix (which may take a while?) is do you have any suggestions for a workaround?

**Comment by newpavlov** [comment] 2019-06-19 16:50
Have you tried to compile your project with RUSTFLAGS environmental variable set via console? IIRC everything works as intended with it.

**Comment by dvdplm** [comment] 2019-06-19 17:08
@newpavlov yes we have and yes it does. For various reasons we preferred using `.cargo/config` to set the flags but for the time being using the env var seems to be the least painful way.
