### ISSUE TITLE
out of range for slice of length 16 

### ISSUE THREAD

**Issue by cssivision** [RustCrypto/stream-ciphers#260] opened 2021-08-04 10:15 UTC
aes-256-cfb, after run a period of time, got error: 
thread 'main' panicked at 'range end index 8444544247700826640 out of range for slice of length 16', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cfb-mode-0.7.1/src/lib.rs:85:33

**Comment by newpavlov** [comment] 2021-08-05 15:03
Are you sure you don't have UB somewhere in your code? Because it looks like a memory corruption issue to me. For some reason you get `pos` equal to to 8444544247700826640, even though it's set either to 0, or to a number of [remaining bytes](https://github.com/RustCrypto/stream-ciphers/blob/cfb-mode-v0.7.1/cfb-mode/src/lib.rs#L104), which is always smaller than 16 for AES block ciphers.

**Comment by cssivision** [comment] 2021-08-05 15:40
thanks for the reply. I'm sure there is no unsafe code. and 'pos' is not exported, i hava no change to change it.

**Comment by newpavlov** [comment] 2021-08-05 15:44
Then I will need a minimal example which would reproduce this issue. Iterating encryption 10k times with different chunk sizes does not trigger it.

**Comment by newpavlov** [comment] 2021-08-05 22:31
FYI here is the test function which I was using:
```rust
#[test]
fn foo() {
    use cfb_mode::cipher::{NewCipher, AsyncStreamCipher};
    let k = Default::default();
    let iv = Default::default();
    let mut mode = Cfb::<aes::Aes128>::new(&k, &iv);
    let mut buf = [42; 256];
    let mut n = 0u8;
    for _ in 0..1_000_000 {
        getrandom::getrandom(core::slice::from_mut(&mut n)).unwrap();
        mode.encrypt(&mut buf[..n as usize]);
        let p = mode.get_pos();
        assert!(p < 16);
    }
}
```
It always passes without issues, so it's highly unlikely that the problem is caused by a bug in the `cfb-mode` crate. Check your code and dependencies carefully. There is also a possibility that you've encountered a miscompilation bug (probability of it is quite low, but we have encountered it several times), so try different compiler versions.

I will leave this issue open for several days, but if you will not manage to reproduce the issue, I think I will close it.

**Comment by cssivision** [comment] 2021-08-06 02:26
I can't reproduce the issue, my program run several days and never happen again. feel free to close it.

**Closed** 2021-08-09 03:13 UTC
